language: python
python:
    - "2.7"
    - "3.4"

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements-py2.txt; fi
    - "pip install -r requirements.txt"
script: "py.test tests/ --cov garcon --cov-report term-missing"
after_success:
    - coveralls
